version: '3.8'

networks:
  elastic:
    driver: bridge
    external: false

services:
  app:
   build: .
   container_name: app
   image: app
   environment:
     - ELASTICSEARCH_URL=elasticsearch:9200
   ports:
     - 8080:8080
   networks:
     - elastic
   depends_on:
    - elasticsearch





  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - cluster-name=elastic-cluster
      - xpack.security.enabled=false
#      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=elasticsearch-01
      - cluster.initial_master_nodes=elasticsearch-01,elasticsearch
      - discovery.seed_hosts=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic


  elasticsearch-01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch-01
    volumes:
      - elasticsearch-data-01:/usr/share/elasticsearch/data

    environment:
      - cluster-name=elastic-cluster
      - xpack.security.enabled=false
#      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=elasticsearch-01
      - cluster.initial_master_nodes=elasticsearch-01,elasticsearch
      - discovery.seed_hosts=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic




volumes:
  elasticsearch-data:
    driver: local
  elasticsearch-data-01:
    driver: local


